"""Migrations

Revision ID: bb3a2c880222
Revises: aedbe5030372
Create Date: 2024-06-28 15:15:39.948909

"""

# revision identifiers, used by Alembic.
revision = "bb3a2c880222"
down_revision = "aedbe5030372"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
